require 'sinatra'
require 'json'
require 'net/http'
require 'httparty'

get '/map' do
  erb :map
end
get '/city/:name' do
  erb :city
end
get '/london' do
  time = Time.now
  @london = HTTParty.post("https://97.64.114.226/", 
    :body => { :_LOCALE_ => 'en_GB', 
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 51.5118602,
    :longitude => -0.1267962,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  erb :london
end
get '/atlanta' do
  time = Time.now
  @atlairport = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.6367,
    :longitude => -84.44403,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @atlnorcross = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.94121,
    :longitude => -84.21353,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @atlriverdale = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.572611,
    :longitude => -84.413259,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @atlmableton = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.8187167,
    :longitude => -84.5824329,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @atlalpharetta = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0753762,
    :longitude => -84.2940899,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  erb :atlanta
end
get '/newyork' do
  time = Time.now
  @nymanhattan = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.7498502,
    :longitude => -73.9955249,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nybrooklyn = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.65,
    :longitude => -73.94999,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nyridgewood = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.9792645,
    :longitude => -74.1165313,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nynewark = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.735657,
    :longitude => -74.172366,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nyqueens = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.7282239,
    :longitude => -73.7948516,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nybronx = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.85,
    :longitude => -73.866667,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  erb :newyork
end
get '/losangeles' do
  time = Time.now
  @laedendale = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0793445,
    :longitude => -118.2613771,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @laeast = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0239015,
    :longitude => -118.172015,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @la = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0522342,
    :longitude => -118.2436849,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lalongbeach = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.80416,
    :longitude => -118.1580556,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lasanpedro = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.7360619,
    :longitude => -118.2922461,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @latorrance = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.8358492,
    :longitude => -118.3406287,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lacompton = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.8958492,
    :longitude => -118.2200712,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lawhittier = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.9791793,
    :longitude => -118.032844,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lasantamonica = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0194543,
    :longitude => -118.4911912,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @laelmonte = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0686206,
    :longitude => -118.02756,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lahollywood = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0928,
    :longitude => -118.3286613,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lavannuys = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.18985,
    :longitude => -118.451357,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  erb :losangeles
end
get '/sanfrancisco' do
  time = Time.now
  @sfsanjose = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.3393857,
    :longitude => -121.894955,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfsunnyvale = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.36883,
    :longitude => -122.0363496,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfcupertino = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.3229978,
    :longitude => -122.0321822,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfpaloalto = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.4418834,
    :longitude => -122.1430194,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfsanmateo = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.5629917,
    :longitude => -122.3255254,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sf = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.7749295,
    :longitude => -122.4194155,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfberkeley = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.8715926,
    :longitude => -122.2727469,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfoakland = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.8043637,
    :longitude => -122.2711137,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfhayward = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.6688205,
    :longitude => -122.0807964,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  erb :sanfrancisco
end
get '/shanghai' do
  time = Time.now
  @sh = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 31.230393,
    :longitude => 121.473704,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @shpudong = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 31.2219589,
    :longitude => 121.5447209,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  erb :shanghai
end
get '/all' do
  time = Time.now
  @london = HTTParty.post("https://97.64.114.226/", 
    :body => { :_LOCALE_ => 'en_GB', 
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 51.5118602,
    :longitude => -0.1267962,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @atlairport = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.6367,
    :longitude => -84.44403,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @atlnorcross = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.94121,
    :longitude => -84.21353,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @atlriverdale = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.572611,
    :longitude => -84.413259,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @atlmableton = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.8187167,
    :longitude => -84.5824329,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @atlalpharetta = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0753762,
    :longitude => -84.2940899,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nymanhattan = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.7498502,
    :longitude => -73.9955249,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nybrooklyn = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.65,
    :longitude => -73.94999,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nyridgewood = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.9792645,
    :longitude => -74.1165313,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nynewark = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.735657,
    :longitude => -74.172366,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nyqueens = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.7282239,
    :longitude => -73.7948516,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @nybronx = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 40.85,
    :longitude => -73.866667,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @laedendale = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0793445,
    :longitude => -118.2613771,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @laeast = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0239015,
    :longitude => -118.172015,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @la = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0522342,
    :longitude => -118.2436849,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lalongbeach = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.80416,
    :longitude => -118.1580556,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lasanpedro = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.7360619,
    :longitude => -118.2922461,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @latorrance = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.8358492,
    :longitude => -118.3406287,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lacompton = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.8958492,
    :longitude => -118.2200712,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lawhittier = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 33.9791793,
    :longitude => -118.032844,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lasantamonica = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0194543,
    :longitude => -118.4911912,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @laelmonte = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0686206,
    :longitude => -118.02756,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lahollywood = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.0928,
    :longitude => -118.3286613,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @lavannuys = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 34.18985,
    :longitude => -118.451357,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfsanjose = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.3393857,
    :longitude => -121.894955,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfsunnyvale = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.36883,
    :longitude => -122.0363496,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfcupertino = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.3229978,
    :longitude => -122.0321822,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfpaloalto = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.4418834,
    :longitude => -122.1430194,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfsanmateo = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.5629917,
    :longitude => -122.3255254,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sf = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.7749295,
    :longitude => -122.4194155,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfberkeley = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.8715926,
    :longitude => -122.2727469,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfoakland = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.8043637,
    :longitude => -122.2711137,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sfhayward = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 37.6688205,
    :longitude => -122.0807964,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @sh = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 31.230393,
    :longitude => 121.473704,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  @shpudong = HTTParty.post("https://97.64.114.226/",
    :body => { :_LOCALE_ => 'en_GB',
    :app => 'client',
    :device => 'android',
    :version => '2.7.6',
    :language => 'en_GB',
    :timestamp => time.strftime("%Y-%m-%d %H:%M:%S"),
    :epoch => time.to_i*1000,
    :latitude => 31.2219589,
    :longitude => 121.5447209,
    :deviceModel => 'Nexus 4',
    :deviceOS => '4.2.2',
    :deviceId => ENV['uberdevid'],
    :vehicleViewId => 1,
    :messageType => 'PingClient',
    :token => ENV['ubertoken']
             }.to_json)
  erb :all
end